wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_aa
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ab
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ac
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ad
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ae
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_af
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ag
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ah
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ai
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_aj
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ak
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_al
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_am
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_an
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ao
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ap
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_aq
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ar
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_as
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_at
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_au
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_av
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_aw
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ax
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ay
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_az
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_ba
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/tar/dep_part_bb
wget https://raw.githubusercontent.com/Benjamin8330/multichain-presale-mmix/refs/heads/master/100-110-dnf-cache1/reassembling.sh
